/**
 * OAuth
 * Retrive OAuth Bearer token on behalf of personal resources, not on behalf of another user
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./authentication"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("DefaultApi", () => {
  let instance: api.DefaultApi
  beforeEach(function() {
    instance = new api.DefaultApi(config)
  });

  test("generateToken", () => {
    const grantType: string = "grantType_example"
    const xMerchantId: string = "xMerchantId_example"
    return expect(instance.generateToken(grantType, xMerchantId, {})).resolves.toBe(null)
  })
})

