/**
 * Rate
 * The Rating API is used when rating or shopping a shipment.
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./rating"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("DefaultApi", () => {
  let instance: api.DefaultApi
  beforeEach(function() {
    instance = new api.DefaultApi(config)
  });

  test("rate", () => {
    const body: api.RATERequestWrapper = {
  "summary" : "Simple Rate Example",
  "value" : {
    "RateRequest" : {
      "Request" : {
        "TransactionReference" : {
          "CustomerContext" : "CustomerContext",
          "TransactionIdentifier" : "TransactionIdentifier"
        }
      },
      "Shipment" : {
        "Shipper" : {
          "Name" : "ShipperName",
          "ShipperNumber" : "ShipperNumber",
          "Address" : {
            "AddressLine" : [ "ShipperAddressLine", "ShipperAddressLine", "ShipperAddressLine" ],
            "City" : "TIMONIUM",
            "StateProvinceCode" : "MD",
            "PostalCode" : "21093",
            "CountryCode" : "US"
          }
        },
        "ShipTo" : {
          "Name" : "ShipToName",
          "Address" : {
            "AddressLine" : [ "ShipToAddressLine", "ShipToAddressLine", "ShipToAddressLine" ],
            "City" : "Alpharetta",
            "StateProvinceCode" : "GA",
            "PostalCode" : "30005",
            "CountryCode" : "US"
          }
        },
        "ShipFrom" : {
          "Name" : "ShipFromName",
          "Address" : {
            "AddressLine" : [ "ShipFromAddressLine", "ShipFromAddressLine", "ShipFromAddressLine" ],
            "City" : "TIMONIUM",
            "StateProvinceCode" : "MD",
            "PostalCode" : "21093",
            "CountryCode" : "US"
          }
        },
        "PaymentDetails" : {
          "ShipmentCharge" : {
            "Type" : "01",
            "BillShipper" : {
              "AccountNumber" : "ShipperNumber"
            }
          }
        },
        "Service" : {
          "Code" : "03",
          "Description" : "Ground"
        },
        "NumOfPieces" : "1",
        "Package" : {
          "SimpleRate" : {
            "Description" : "SimpleRateDescription",
            "Code" : "XS"
          },
          "PackagingType" : {
            "Code" : "02",
            "Description" : "Packaging"
          },
          "Dimensions" : {
            "UnitOfMeasurement" : {
              "Code" : "IN",
              "Description" : "Inches"
            },
            "Length" : "5",
            "Width" : "5",
            "Height" : "5"
          },
          "PackageWeight" : {
            "UnitOfMeasurement" : {
              "Code" : "LBS",
              "Description" : "Pounds"
            },
            "Weight" : "1"
          }
        }
      }
    }
  }
}
    const version: string = "version_example"
    const requestoption: string = "requestoption_example"
    const transId: string = "transId_example"
    const transactionSrc: string = "transactionSrc_example"
    const additionalinfo: string = "additionalinfo_example"
    return expect(instance.rate(body, version, requestoption, transId, transactionSrc, additionalinfo, {})).resolves.toBe(null)
  })
})

